---
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
install:
  - make install
  - sls dynamodb install
before_script:
  - sls dynamodb start & sleep 5
script:
  - make test-coverage
after_script:
  - cat coverage/lcov.info | coveralls
  - make deploy
  - make deploy-production-eu
  - make deploy-production-us
branches:
  only:
    - master
